### ISSUE TITLE
can this lapack package be used with conda/pip and mingw for building scipy on windows?

### ISSUE THREAD

**Issue by denfromufa** [conda-forge/lapack-feedstock#10]
Original question here: https://mail.python.org/pipermail/scipy-user/2017-May/037195.html

**Comment by denfromufa** [comment]
If yes, what options should be passed to pip/conda/distutils/setuptools/setup.py?

**Comment by jschueller** [comment]
Maybe, as it's using mingw also. You can also look at the openblas recipe.
