### ISSUE TITLE
lapack.lib appears to be missing from the built Windows package

### ISSUE THREAD

**Issue by anntzer** [conda-forge/lapack-feedstock#31]
Downloading the .tar.bz2 windows package from https://anaconda.org/conda-forge/liblapack/files (whether the openblas or the mkl version) shows that lapack.lib is missing from the package.  I am confused as to why, given that the file is explicitly listed in https://github.com/conda-forge/lapack-feedstock/blob/master/recipe/meta.yaml#L116; help would be most welcome.

(This file is needed to link against lapack on Windows.)

**Comment by isuruf** [comment]
@anntzer, you need to use the `netlib` version if you want `lapack.lib`

**Comment by anntzer** [comment]
Is that available in any conda channel?

**Comment by isuruf** [comment]
Yes, see https://anaconda.org/conda-forge/liblapack/files (search for netlib)

**Comment by anntzer** [comment]
Ah, great, thanks :)
