### ISSUE TITLE
Using libgcc and libgfortran?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/lapack-feedstock#4]
We appear to be using both `libgcc` and `libgfortran` on UNIX. However we should only need one. Preferably it should be `libgfortran` unless we need something else like C++. Thoughts @jschueller ?

**Comment by jschueller** [comment]
Yes, I think it should be just libgfortran

**Comment by jakirkham** [comment]
Addressing in PR ( https://github.com/conda-forge/lapack-feedstock/pull/5 ).
