### ISSUE TITLE
Missing lapack.pc

### ISSUE THREAD

**Issue by moorepants** [conda-forge/lapack-feedstock#45]
Issue:

I've used pkg-config on upstream packages in the past to discover the compilation flags for lapack. Recently, it seems the lapack.pc file may be missing. I had a successful build on Sept 24 here: https://travis-ci.org/github/matthias-k/cyipopt/jobs/730025702 but now have a failing build here: https://travis-ci.org/github/matthias-k/cyipopt/jobs/746326298. I don't think I have any related changes on my end. When I search my local ~/miniconda/lib/pkgconfig I don't see a `lapack.pc` file. Is it possible this has been removed recently?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by moorepants** [comment]
I see that the Sept 24 working build had lapack 3.8.0 and the failing build has lapack 3.9.0. I'll try building with lapack < 3.9.0.

**Comment by moorepants** [comment]
I used `lapack<3.9.0` and the build suceeded, finding the `lapack.pc` file. So it seems the file is not being provided with version 3.9.0.

**Comment by moorepants** [comment]
You can see here that I install `lapack` in a conda env, conda list shows it installed, but then I `ls` the `miniconda/envs/<my-env>/lib/pkgconfg` directory and none of the pc files from this package are present.

https://travis-ci.org/github/matthias-k/cyipopt/jobs/746495141

**Comment by isuruf** [comment]
Closing in favour of https://github.com/conda-forge/openblas-feedstock/issues/112
