### ISSUE TITLE
Add a libtmglib output just like libblas

### ISSUE THREAD

**Issue by isuruf** [conda-forge/lapack-feedstock#48]
@hhslepicka if you can help with this, we can fix this faster.

**Comment by hhslepicka** [comment]
I can give it a try if you give me some info on that...

**Comment by isuruf** [comment]
Sure. I think it's as easy as duplicating https://github.com/conda-forge/lapack-feedstock/blob/master/recipe/meta.yaml#L63-L89 and then `s/libblas/libtmglib/g` and then duplicating https://github.com/conda-forge/lapack-feedstock/blob/master/recipe/meta.yaml#L199 as well.

**Comment by hhslepicka** [comment]
I will take a stab at it... thanks for the info...
