### ISSUE TITLE
blis dependency missing?

### ISSUE THREAD

**Issue by ax3l** [conda-forge/lapack-feedstock#57]
It looks to me like this feedstock might depend directly on `blis` for **Windows** but does not declare that dependency. Is  that possible?

Seeing downstream issues in `LAPACK++`: https://github.com/conda-forge/lapackpp-feedstock/pull/2

```
-- Found LAPACK: D:/bld/lapackpp_1638899736446/_h_env/Library/lib/lapack.lib;D:/bld/lapackpp_1638899736446/_h_env/Library/lib/blis.lib;-fortranlibs  
...

(%BUILD_PREFIX%) %SRC_DIR%>cmake --build build --config Release --parallel 2 
ninja: error: 'D:/bld/lapackpp_1638899736446/_h_env/Library/lib/blas.lib', needed by 'lapackpp.dll', missing and no known rule to make it
```

**Comment by ax3l** [comment]
Hm, unclear to me. Something is off.

**Comment by jakirkham** [comment]
Was this meant to be closed @ax3l?

**Comment by ax3l** [comment]
I am not sure why `blis` show up in the dependencies list, but maybe that's a downstream problem in https://github.com/conda-forge/lapackpp-feedstock/pull/2

Did not find `blis` in the build logs of the `lapack` feedstock here, so I guess that direction is not causing it. Looks more like a Fortran definition issue right now in LAPACK++.

**Comment by h-vetinari** [comment]
I saw that Isuru already jumped in onto that PR, but just to explain:
- this feedstock packages _only_ the "netlib" variant of blas/lapack from https://github.com/Reference-LAPACK/lapack.
- the actual blas/lapack packages that almost everyone uses come from https://github.com/conda-forge/blas-feedstock, which goes to quite some length to be able to create additional flavours (openblas, mkl, blis) for blas/lapack in conda-forge.

The way things are then handled in conda-forge is that - generally - everything is _compiled against_ the "netlib" reference variant, which can then be replaced with a given blas flavour at runtime (by which I mean runtime-dependencies).

**Comment by ax3l** [comment]
Thanks a lot for the details, @h-vetinari!
That clarifies a lot for me :tada:

**Comment by ax3l** [comment]
Now I saw that bliss dependency problem downstream again:
https://github.com/conda-forge/warpx-feedstock/pull/35#issuecomment-991751045

Am I forgetting to load something BLAS/LAPACK related?

**Comment by isuruf** [comment]
Yes, I don't know why you reverted some of my changes in https://github.com/conda-forge/lapackpp-feedstock/commit/102dc1c269e3e2c3a505354d7665f5dd9aa88dfc#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a
If that is fixed, then there should be no error.

**Comment by ax3l** [comment]
Ah, sorry for that. I added the same thing at some point but had no error removing it. thought it was testing and cleaned up.

Thanks and sorry again!

On December 11, 2021 11:39:10 AM PST, Isuru Fernando ***@***.***> wrote:
>Yes, I don't know why you reverted some of my changes in https://github.com/conda-forge/lapackpp-feedstock/commit/102dc1c269e3e2c3a505354d7665f5dd9aa88dfc#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9a
>If that is fixed, then there should be no error.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/conda-forge/lapack-feedstock/issues/57#issuecomment-991761626
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ax3l** [comment]
Just to complete my understanding: do packages that depend on `lapackpp`/`blaspp` also have to add `libblas` and `liblapack` in their `host` dependencies? Or is it enough that these direct dependencies list them?

**Comment by isuruf** [comment]
No, it's enough that `lapackpp` and `blaspp` have them listed.

**Comment by ax3l** [comment]
Thanks! Hm, ok I tried this but in some cases it seems needed. Might be due to LAPACK++/BLAS++ CMake config scripts:
https://github.com/conda-forge/warpx-feedstock/pull/35
